version: '3.8'

networks:
  mysql-net:
    name: mysql-net

volumes:
  mysql-vol: {}


services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --bind-address=0.0.0.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=1234
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=
    networks:
      - mysql-net
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - mysql-vol:/var/lib/mysql
    healthcheck:
      test: MYSQL_PWD=$$MYSQL_ROOT_PASSWORD mysqladmin -h `hostname -i` -P 3306 -u root --silent ping
      start_period: 20s
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:latest
    container_name: adminer
    healthcheck:
      interval: 5s
      retries: 5
      start_period: 20s
      test: ['CMD', 'wget', '--no-verbose', '--spider', 'http://localhost:8080']
      timeout: 5s
    depends_on:
      - mysql
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
      - ADMINER_DESIGN=flat
      - ADMINER_PLUGINS=dump-zip dump-json edit-foreign json-column tables-filter tinymce
    ports:
      - 8080:8080
    networks:
      - mysql-net
    restart: unless-stopped

